<div class="app_contactUs">
  <ul class="app_contactUs_list">
    <li class="app_contactUs_list_item top" title="点我回到顶部">
      <a href="#top" class="app_contactUs_list_item_link">
        <div class="app_contactUs_list_item_link_img"></div>
      </a>
    </li>
    <li class="app_contactUs_list_item">
      <a href="javascript:void(0)" class="app_contactUs_list_item_link wx">
        <div class="app_contactUs_list_item_link_img"></div>
        <div class="app_contactUs_list_item_link_ewmBox">
          <div class="app_contactUs_list_item_link_ewmBox_imgBox">
            <div class="app_contactUs_list_item_link_ewmBox_imgBox_text">扫码关注：</div>
            <div class="app_contactUs_list_item_link_ewmBox_imgBox_img"></div>
          </div>
        </div>
      </a>
    </li>
    <li class="app_contactUs_list_item">
      <a href="tencent://message/?uin=907468866&Site=&Menu=yes" class="app_contactUs_list_item_link qq">
        <div class="app_contactUs_list_item_link_img"></div>
        <div class="app_contactUs_list_item_link_ewmBox">
          <div class="app_contactUs_list_item_link_ewmBox_imgBox">
            <div class="app_contactUs_list_item_link_ewmBox_imgBox_text">点击联系我：</div>
            <div class="app_contactUs_list_item_link_ewmBox_imgBox_img"></div>
          </div>
        </div>
      </a>
    </li>
    <li class="app_contactUs_list_item foot">
      <a href="tel:037179856358" class="app_contactUs_list_item_link tel">
        <div class="app_contactUs_list_item_link_img"></div>
        <div class="app_contactUs_list_item_link_ewmBox">
          <div class="app_contactUs_list_item_link_ewmBox_imgBox">
            <div class="app_contactUs_list_item_link_ewmBox_imgBox_text">点击联系我：<br/>0371-79856358</div>
            <div class="app_contactUs_list_item_link_ewmBox_imgBox_img"></div>
          </div>
        </div>
      </a>
    </li>
  </ul>
</div>
