<div class="app_body2_con_db">
  <div class="app_body2_con_db_left">
    <div class="app_body2_con_db_left_logo"></div>
    <div class="app_body2_con_db_left_text">@ 2017 嘟嘟应用中心</br>豫ICP备14012584号</div>
    <div class="app_body2_con_db_left_erweima"></div>
  </div>
  <div class="app_body2_con_db_right">
    <ul class="app_body2_con_db_right_list">
      <li class="app_body2_con_db_right_list_item">
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">关于我们</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">关于我们</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">H5应用中心</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">幅度达到</a>
      </li>
      <li class="app_body2_con_db_right_list_item">
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">帮助中心</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">怎没使用</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">怎么购买</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">怎么续费</a>
      </li>
      <li class="app_body2_con_db_right_list_item">
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">友情链接</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">嘟嘟微生活</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">嘟嘟商学院</a>
        <a href="javascript:void(0)" class="app_body2_con_db_right_list_item_a">嘟嘟微聚</a>
      </li>
    </ul>
  </div>
</div>
