<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<!-- 开发pc -->
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
	
	<link href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css" rel="stylesheet">
	<script src="//cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>

	<!-- 开发移动 -->
	<!-- 上线时打开注释 -->
	<!-- <meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"> -->
	<!-- <script src="js/flexible.js"></script>
	<link rel="stylesheet" href="css/index.css" />
	<link href="//cdn.bootcss.com/aos/1.2.2/aos.css" rel="stylesheet">
	<script src="//cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
	<script src="//cdn.bootcss.com/aos/1.2.2/aos.js"></script> -->

</head>
